import { useEffect, useState } from "react";
import { Activity, BookOpen, CircleHelp, Clock3, GraduationCap, LayoutDashboard, MessageSquareText, Monitor, Play, Settings2, ShieldCheck, Square, WifiOff } from "lucide-react";

type Status = { product: string; engine: string; ufo_installed: boolean; execution_api_available: boolean; notes?: string[] };
const pages = [{name:"Trợ lý AI",Icon:MessageSquareText},{name:"Dạy AI công việc",Icon:GraduationCap},{name:"Thư viện kỹ năng",Icon:BookOpen},{name:"Lịch sử tác vụ",Icon:Clock3},{name:"Cài đặt",Icon:Settings2}];
export default function App(){
 const [active,setActive]=useState("Trợ lý AI");
 const [status,setStatus]=useState<Status|null>(null);
 const [error,setError]=useState("");
 const [prompt,setPrompt]=useState("");
 const [messages,setMessages]=useState<{role:"user"|"system",content:string}[]>([{role:"system",content:"Xin chào! Đây là giao diện SmartAutomation đang phát triển. Hiện chưa bật điều khiển máy tính qua chat; chúng ta sẽ kết nối UFO sau khi có quản lý tác vụ và nút dừng an toàn."}]);
 useEffect(()=>{fetch("/api/status").then(async r=>{if(!r.ok) throw new Error("Không kết nối được API");setStatus(await r.json())}).catch(()=>setError("API chưa chạy — hãy khởi động FastAPI tại 127.0.0.1:8765"))},[]);
 function send(){const value=prompt.trim();if(!value)return;setMessages(x=>[...x,{role:"user",content:value},{role:"system",content:"Đã ghi nhận yêu cầu trong giao diện thử nghiệm. Chưa thực thi hành động Windows; tính năng này đang chờ kết nối UFO và cơ chế dừng an toàn."}]);setPrompt("")}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Monitor size={21}/></div><div><strong>SmartAutomation</strong><small>AI Desktop Assistant</small></div></div><nav>{pages.map(({name,Icon})=><button key={name} className={active===name?"nav active":"nav"} onClick={()=>setActive(name)}><Icon size={18}/>{name}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">SA</div><div><strong>Local Workspace</strong><small>Microsoft UFO</small></div></div></aside><main className="main"><header><div><span className="eyebrow">WORKSPACE</span><h1>{active}</h1></div><div className="status"><span className={status?.ufo_installed?"dot success":"dot"}></span>{status?.ufo_installed?"Đã phát hiện UFO":"Chưa sẵn sàng"}</div></header>{active==="Trợ lý AI"?<div className="workspace"><section className="chat"><div className="chat-head"><div className="icon-circle"><MessageSquareText size={18}/></div><div><strong>Hội thoại với SmartAutomation</strong><p>Ra lệnh bằng tiếng Việt để điều khiển công việc</p></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={m.role==="user"?"bubble user":"bubble system"}>{m.content}</div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Yêu cầu cho SmartAutomation" placeholder="Ví dụ: Mở Excel, tổng hợp báo cáo tháng này..." value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button type="submit" aria-label="Gửi yêu cầu"><Play size={19}/></button></form><div className="hint"><ShieldCheck size={14}/> Chế độ an toàn: giao diện chưa được phép điều khiển máy</div></section><aside className="inspector"><div className="panel"><div className="panel-title"><Activity size={18}/>Trạng thái hệ thống</div><dl><dt>Engine</dt><dd>Microsoft UFO</dd><dt>AI</dt><dd>Cấu hình tại máy</dd><dt>Quyền thực thi qua UI</dt><dd>Chưa bật</dd></dl>{error&&<p className="warning"><WifiOff size={15}/>{error}</p>}{status?.notes?.map((n,i)=><p className="minor" key={i}>{n}</p>)}</div><div className="panel"><div className="panel-title"><LayoutDashboard size={18}/>Tiến trình tác vụ</div><div className="empty"><CircleHelp size={24}/><strong>Chưa có tác vụ đang chạy</strong><span>Tiến độ và nhật ký UFO sẽ xuất hiện tại đây.</span></div><button className="stop" disabled><Square size={16}/> Dừng khẩn cấp (chưa kết nối)</button></div></aside></div>:<section className="placeholder"><div className="big-icon">{active==="Dạy AI công việc"?<GraduationCap/>:active==="Thư viện kỹ năng"?<BookOpen/>:active==="Lịch sử tác vụ"?<Clock3/>:<Settings2/>}</div><h2>{active}</h2><p>Đang chuẩn bị tích hợp tính năng này với Microsoft UFO. Hiện chưa có dữ liệu nghiệp vụ hoặc kỹ năng được lưu.</p><span className="coming">Sắp triển khai</span></section>}</main></div>
}
